### PR TITLE
Added room timeout

### PR DESCRIPTION
**Pull request by Codeacious**

### CODE REVIEW

**Comment by max-b** [comment]
It seems like maybe that upstream commit got included here?

**Comment by Codeacious** [comment]
It did; I'm not seeing conflicts w/ main though so we can marge this then pull in upstream?

**Comment by max-b** [comment]
> It did; I'm not seeing conflicts w/ main though so we can marge this then pull in upstream?

Yeah in general I'm not personally a big fan of merge commits and it doesn't look like the upstream codebase is using them either, but I'm also trying not to be too dogmatic/neurotic/a PITA about it so I'm happy w/ whichever you'd prefer

**Comment by max-b** [comment]
oh I'm realizing this is also more complicated since this is just basically a built artifact from the main livekit repo :grimacing: 

protobufs were a mistake

**Review by max-b — APPROVED** [review]

**Comment by max-b** [comment]
let's go w/ whatever is easiest here

**Pull request merged**
